### ISSUE TITLE
Add Icon on configuration page throws error for non-image types

### ISSUE THREAD

**Issue by bryanhiggins** [blackberry/webworks-gui#102]
Steps to reproduce 
-Create a project 
-Go to configuration page 
-Add a valid non-image path to the icon textbox [i.e ./css] 
-Click Add Icon 

Actual 
-GUI doesn't inform user to enter a valid image 
-Error in console 

Expected 
-GUI informs user to insert a "valid" image, similar to the error shown with invalid paths 
-No error in console

If user happens to save this state, an invalid css entry is added to config.xml and next time they attempt to open the configuration page, the icon and splash screen input elements do not show up at all.

**Comment by rcruz** [comment]
Which file extensions are considered valid? The universe of image file extensions is quite large. (.raw, .tiff, etc). Our published docs say only .png is supported. Is .png only something we should enforce?
