### ISSUE TITLE
As a WebWorks developer, I can deploy my application from the GUI tool to a device over WiFi

### ISSUE THREAD

**Issue by kwallis** [blackberry/webworks-gui#11]
## Description

While USB detection is great, we should also support deployment to a device over wifi
## Acceptance Criteria
- Developer should be able to input an IP address that will be used for deployment
- Developer should be able to save an IP address as a "preset" with an associated user-defined friendly name to describe that "target"
- Developer should be able to select a preset "target" for deployment.
- Developer should be able to delete a preset.

**Comment by bryanhiggins** [comment]
There should be a top-level screen for managing targets. This will invoke the "webworks target" command.

The build and deploy screen should have a dropdown for selecting deployment target. Default is "Autodetect".

**Comment by rcruz** [comment]
I think this should be done with a 2 page system -- one page to show the target list, one page to show target details. Currently, the CLI command "webworks target" doesn't support this feature set but if we bypass the CLI, we can directly edit the target json file at .cordova/blackberry10.json

A proposed target list page will look similar to the plugin list page, with the following differences:

The "ADD TARGET" button will change views to a details page where the user can enter info.
Each target in the list will have a gear icon to the left of trash icon. This icon will take the user to the details page when clicked.

Thoughts?
