### ISSUE TITLE
As a WebWorks developer, I have a link on the Certificates page that takes me to the registration page on BlackBerry to get my token

### ISSUE THREAD

**Issue by kwallis** [blackberry/webworks-gui#121]
There should be a link on the certificates page that takes me to the registration page for BBID-based signing certificates.

https://developer.blackberry.com/codesigning

cc @bryanhiggins

**Comment by bryanhiggins** [comment]
Related to #83 

I think this page should be organized into steps. Step 1 is downloading the CSK.

**Comment by kwallis** [comment]
Yeah, I was thinking though that this might be a quick intermediate step we could do in 2.1?

**Comment by bryanhiggins** [comment]
#83 is in the 2.1 milestone

**Comment by kwallis** [comment]
Well i'll be...

**Comment by kwallis** [comment]
Well i'll be...

**Comment by kwallis** [comment]
Well i'll be...
