### ISSUE TITLE
Rename "autodetect" to "USB / Simulator" or "Simulator / USB"

### ISSUE THREAD

**Issue by jsoref** [blackberry/webworks-gui#128]
"autodetect" (which perhaps should be "auto detect" or "auto-detect") doesn't really explain what it does.

We should change the option to be self-describing. If it favors USB, it should be "USB / Simulator", if it favors Simulator, it should be "Simulator / USB"

**Comment by rcruz** [comment]
@bryanhiggins Is USB connected device preferred over simulator when using "webworks run"?

**Comment by bryanhiggins** [comment]
The run command is not used for simulators. In fact, we should really be filtering the target list based on the user's selection of device or simulator.

**Comment by bryanhiggins** [comment]
I stand corrected - there is no toggle on the UI for device vs simulator.

@rcruz how does the GUI detect simulator? try emulate after run fails?

**Comment by rcruz** [comment]
A toggle in the UI used to exist. It appears to have been removed by recent target changes. I believe there are still use cases where we need the device/simulator toggle and this should not have been removed.

**Comment by bryanhiggins** [comment]
So I'm not crazy after all! :)

**Comment by jsoref** [comment]
Aren't you glad I filed this bug? :)

**Comment by bryanhiggins** [comment]
Fixed by #161
