### ISSUE TITLE
Offer "Install" button

### ISSUE THREAD

**Issue by jsoref** [blackberry/webworks-gui#141]
Currently we have:

[ Build ] [ Build & Install ]

We should have:

[ Build ] [ Install ]
[ Build & Install ]

**Comment by rcruz** [comment]
@kwallis @bryanhiggins Are we adding this to 2.1?

**Comment by kwallis** [comment]
Impact to adding this? Amount of work and risk?

**Comment by jsoref** [comment]
It lets people who just want to install w/o waiting to rebuild click a single button.
It avoids signing requests to the network (especially if you don't have a network) when they really shouldn't be needed.

Amount of work: a few minutes (I can do it).

**Comment by bryanhiggins** [comment]
This request came from an enterprise end user. I suggest we add it :)

**Comment by kwallis** [comment]
Fine with me
