### ISSUE TITLE
Debug token always deploying when building & installing

### ISSUE THREAD

**Issue by thtro** [blackberry/webworks-gui#157]
Hello,
I'm wondering, why the debug token is always deployed to the device, even if it detects that the existing token is valid, it seems an additional waste of time to the already slow building process.. Don't know if this has to do with the CLI or with the GUI tool.

This is the log I see every time I build an app:

[INFO]    Target Z10-2xxxxx selected
[INFO]    The existing debug token is valid
[INFO]    Deploying debug token to target "Z10-2xxxxx"
[INFO]    Sending request: INSTALL_DEBUG_TOKEN
[INFO]    Action: Install Debug Token
[INFO]    File size: 2570
[INFO]    result::success
[INFO]    Populating application source
[INFO]    Parsing config.xml
....................................

Thanks

**Comment by bryanhiggins** [comment]
Hi,

This is part of the CLI, not the GUI.

The message "existing debug token is valid" means the debug token on your host machine includes the PIN of the device you are about to deploy to. This saves time as the token does not need to be regenerated.

Unfortunately, it is not possible to determine if the device has a valid debug token installed, so the script will always upload a new one. There is definitely a trade-off between ease of use and deployment time.

If you find yourself re-deploying the app frequently for debugging, I'd suggest using the serve/perpare commands and set content src in config.xml to your host machine's IP address.

**Comment by thtro** [comment]
Thanks for the fast answer, Bryan. The serve/prepare commands should be integrated in the GUI somehow, I didn't know about them...

Also, there should be a checkbox on whether to actually upload a new debug token or not each time - deploying it each time kinda defeats the purpose of having it installed in the first place, right? :)
Regards

**Comment by bryanhiggins** [comment]
We're discussing that in issue #13

It wouldn't hurt to add a comment there expressing your interest in the feature.

We'll take the checkbox into consideration.

Thanks!
