### ISSUE TITLE
Selecting the Target in the UI results in a "Error accessing file at ..." when there is no blackberry10.json file

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#163]
This occurs when the user had deleted the .cordova directory or when the user is using the UI  (and the tool) for the first time and there is no targets defined.

Linux screen shot:
![screen shot 2014-04-21 at 4 51 27 pm](https://cloud.githubusercontent.com/assets/549345/2760671/321991c0-c9bd-11e3-9338-9d07ba9a0bd0.png)

**Comment by bryanhiggins** [comment]
This was already pointed out in #149 

@rcruz was there a patch for this?

**Comment by bryanhiggins** [comment]
I suggest the GUI uses this module for reading/writing config.

https://github.com/blackberry/cordova-blackberry/blob/v2.1.0/blackberry10/bin/lib/config.js
