### ISSUE TITLE
IE8 and IE9  and is having difficulty rendering the WW SDK UI 2.1.0.8

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#166]
Clicking on buttons is extremely slow. (IF it even renders)
Able to create project (IF you can even get there, but once you have created it, you can't go anywhere else) 

IE10 on Win 8 is having no problems.

Both browsers are reporting that there are errors on the page.

**Comment by rcruz** [comment]
Promoting to 2.1

**Comment by rcruz** [comment]
Slowness appears to be gone with the recent changes. @jengee to confirm

**Comment by jengee** [comment]
SDK 2.1.0.9 renders and executes much faster on IE8 WinXP. Still checking on IE9

**Comment by jengee** [comment]
Hmmmm ... on IE9 WIN7, when initially running the UI, it loads and runs fine. But after clicking on a few different pages (configuration/build/global settings/targets/certificates) the browser starts freezing up. It doesn't matter which pages that I click or the order, this freezing behaviour occurs after a few clicks. When I opened the same UI in firefox, and do the same thing (and open up inspector) I see the following errors:
![screen shot 2014-04-24 at 11 30 09 am](https://cloud.githubusercontent.com/assets/549345/2791299/5e742b4a-cbc5-11e3-94d8-58b4fc794824.png)

Could it be that these errors are causing IE9 to freeze up? It's very possible it's also occuring on IE8 but I haven't clicked around enough to encounter the error.

**Comment by bryanhiggins** [comment]
The IE9 error was reproducible on 2.0 Gold as well, but only on this specific VM. No problems using the official tester from Microsoft.
