### ISSUE TITLE
Hitting return on the "Open Project" page automatically takes you to the Create Project page

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#176]
It's really annoying that after you have entered in the path of the project that you want to open you hit the return button and it takes to the create Project page. 

Can it be set up to submit instead?

**Comment by rcruz** [comment]
Enter button taking you to the "Create project" page is definitely a bug. Promoting to 2.1

**Comment by rcruz** [comment]
The enter button causes the form on the page to submit. This forces the page to reload, which is why the "Create project" screen is displayed.
