### ISSUE TITLE
Configuration page does not save changes when clicking on the same project in "Recent projects"

### ISSUE THREAD

**Issue by jamesjhedley** [blackberry/webworks-gui#185]
-open config page
-make a change to a field (author for instance)
-click on that same project under "Recent Projects"
- *Would you like to save prompt shows
  -click ok to save

Expected
-Changes are saved

Actual
-Changes are lost

Changes are only lost when clicking on the same project.

**Comment by rcruz** [comment]
Promoting to 2.1. We don't want users losing their changes.
