### ISSUE TITLE
"Building..." dialog hangs when no keystore pass provided for release builds

### ISSUE THREAD

**Issue by jamesjhedley** [blackberry/webworks-gui#206]
-go to build page
-select release build mode
-select device type
-leave keystore pass field empty
-select build

Expected
-Error shown "invalid keystore pass" or something similar

Actual
-"Building..." dialog shows and hangs (never goes away)

**Comment by rcruz** [comment]
Resolved by https://github.com/blackberry/webworks-gui/pull/184

**Comment by rcruz** [comment]
That change does not fix this case. We'll need another patch
