### ISSUE TITLE
Target management page saves targets with spaces in their name despite warning in validation

### ISSUE THREAD

**Issue by kflores772** [blackberry/webworks-gui#209]
1. Input a target with a space in the name (ex 'aaa aaa').
2. Input other necessary fields.
3. Click 'update target list'
   Output: warning here saying spaces are not permitted in names
4. Create a new target with correct fields
5. Click 'update target list'
6. Notice that the new target is added to the list as well as 'aaa aaa'

**Comment by jengee** [comment]
Occurs on 2.1.0.13 where users could specify it as SIM name. The output comes out as the following:
The target "My" does not exist, to add that target please run: target add My <ip> [-t | --type <device | simulator>] [-p <password>] [--pin <devicepin>]

Work around is that users would just rename the SIM in the UI with no space.
