### ISSUE TITLE
running UI on Safari 6 results in some errors in the console.log

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#219]
Initially importing a project will result in errors in the console. This does not impact the performance of the UI nor does it stop the user from user the UI.

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3123/js/backbone-min.map

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3123/js/underscore-min.map

**Comment by bryanhiggins** [comment]
Not an issue. Debugger trying to load source maps.
