### ISSUE TITLE
Text box in config panel are not the same size as others in other panels

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#25]
![screen shot 2014-01-16 at 2 07 30 pm](https://f.cloud.github.com/assets/549345/1933842/ac3d6840-7ee1-11e3-8800-7ef70ff83795.png)

![screen shot 2014-01-16 at 2 10 23 pm](https://f.cloud.github.com/assets/549345/1933870/2edc1526-7ee2-11e3-9a7b-39df84700b23.png)

![screen shot 2014-01-16 at 2 11 17 pm](https://f.cloud.github.com/assets/549345/1933859/02d2333e-7ee2-11e3-8537-9b3d91ba40eb.png)

**Comment by kflores772** [comment]
Looks good on IE10, IE8, Firefox 27.0.1
