### ISSUE TITLE
WebWorks Build & Install is not working according to spec

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#26]
The build page for the gui seems to be implementing the wrong behaviour especially for release mode as it still creates a debug token when you do a build and Install.

The following is the expected behaviour for WebWorks GUI Build Page:
# Debug mode button selected:

Click on build and it should run:
1. webworks build --debug 

Click on Build & Install
1. webworks run 
# Release radio button selected:

Click on build it should run
1. webworks build --release

Click on Build & Install should execute the following two commands:
1. webworks build --release
2. webworks run --no-build

**Comment by rcruz** [comment]
Currently "webworks run --no-build" still creates and uploads a debug token, making both methods have the same result
