### ISSUE TITLE
UI unable to install a listed plugin, but then it still shows that it was installed

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#34]
![cmpsoft mobile button error](https://f.cloud.github.com/assets/549345/1946169/9f3d21da-7fef-11e3-956d-cce318c5295e.PNG)
![cmpsoft mobile button error2](https://f.cloud.github.com/assets/549345/1946170/a58f2d1c-7fef-11e3-806a-fca424063bd0.PNG)

But at least you can delete it afterwards.

**Comment by rcruz** [comment]
@themainguru What happens when you do this just with CLI?

**Comment by jengee** [comment]
Retested this SCM WW SDK 2.0.0.59 and the CLI responds with: [Error: Fetching plugin failed: Error: Failed to fetch package information for com.blackberry.community.vibrationYesterday] which is correct. Although I would have preferred that the error  message would be written better but that is different story.
And now the UI on .59 is reflecting the error message but duplicating it
![screen shot 2014-02-10 at 2 35 18 pm](https://f.cloud.github.com/assets/549345/2129711/aaa0a9ea-928a-11e3-80a3-3541749b3426.png)

**Comment by timwindsor** [comment]
I just published that one on the weekend and may have messed something up. Can you test with Prevent Sleep?

**Comment by jengee** [comment]
CLI comes back with a proper error such as: [Error: Fetching plugin failed: Error: Failed to fetch package information for com.blackberry.community.vibrationYesterday]

We definitely need a UI validator that would validate the information that is being passed into the tool. 

@timwindsor For the image: Apparently I did a copy and paste error into the UI and it came back with that nice error message. It's not an error with your plugin at all. In the first line of this comment, I purpose put in a wrong package name in attempt to recreate an error. Don't worry. Your plugin is adds just fine.

**Comment by rcruz** [comment]
Using: 
`webworks plugin add Error Error Error Error`
on CLI produces:
`[Error: Fetching plugin failed: Error: Fetching plugin failed: Error: Fetching plugin failed: Error: Fetching plugin failed: Error: Failed to fetch package information for Error]`

The GUI displays what the CLI produces
