### ISSUE TITLE
Selecting the orientation for the app displays nothing even after selecting one.

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#38]
Selecting the orientation of the app displays nothing even after selecting one or even saving it.

**Comment by jengee** [comment]
Still occuring on Windows 7 -64b latest Chrome version, firefox 27.0.1 and IE 10

On Mac works on Chrome, but does not on firefox latest (24.0)
Can't even confirm this even occurs on Safari 6 as the GUI doesn't work on it.

**Comment by kflores772** [comment]
Works on IE10, IE8, Firefox 27.0.1
