### ISSUE TITLE
UI allows the addition of "" in the access list

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#39]
UI allows the addition of "" in the access list. 

Which will cause problems when building:

C:\Users\jgee\WebWorks Projects\temp_proj>webworks build
[BUILD]   Populating application source
[BUILD]   Parsing config.xml
[ERROR]   Error: Invalid URI attribute in the access element - protocol required(23)
An error has occurred

The UI shouldn't allow you to add something that you can't build it anyway.

![image](https://f.cloud.github.com/assets/549345/1979810/662b05ea-83b6-11e3-8686-722efd2a8bcf.png)

**Comment by rcruz** [comment]
There is currently no validation for most fields in the GUI. Validation requires creating and maintaining a system in which all possible valid values are checked and kept up to date for all fields the user can enter info. To tackle this issue, we need to build this system.
