### ISSUE TITLE
Display: Left list of boxes end up overwriting the main part

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#42]
When ever you have a small screen, it ends up displaying this:

![image](https://f.cloud.github.com/assets/549345/2011149/dfbf1c7a-8776-11e3-8e48-c616c9d346b1.png)

There's gotta be a better way to display this. I have this on a windows VM where the window is always small.

**Comment by jengee** [comment]
This was found on Win7 - IE9

**Comment by bryanhiggins** [comment]
Let's make the menu collapse to the left with an icon to open it
