### ISSUE TITLE
GUI complains that font doesn't exist

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#46]
steps:
1. load http://localhost:3123/
2. check developer console
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3123/fonts/TradeGothicNextLTPro-Rg.otf

manually:
http://localhost:3123/fonts/TradeGothicNextLTPro-Rg.otf
Cannot GET /fonts/TradeGothicNextLTPro-Rg.otf

this is from:
http://localhost:3123/css/base.css
@font-face {
    font-family: bb;
    /_src:url(../fonts/TradeGothicNextLTPro-Rg.otf);_/
    src:url(../fonts/TradeGothicNextLTPro-Rg.otf);
}

![screen shot 2014-02-04 at 1 33 37 pm](https://f.cloud.github.com/assets/549345/2079472/f40d189e-8dca-11e3-9883-fb9dfdb7436d.png)

![missingfont](https://f.cloud.github.com/assets/549345/2079481/fdeee64e-8dca-11e3-9710-3a90f424f5cb.png)

**Comment by bryanhiggins** [comment]
The fonts cannot be included in this repo due to their license.

I have opened an internal issue to have them added to the WebWorks SDK.
