### ISSUE TITLE
Object config does not have widget.preference  

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#47]
1. Create a project in the UI
2. from command line, delete the project in the background.
3. Restart the UI and there is no error handling for projects that don't exist anymore. 

In this case the code assumes that config object has widget.preference component in it.

![screen shot 2014-02-04 at 1 51 30 pm](https://f.cloud.github.com/assets/549345/2079711/b924bd4c-8dcd-11e3-89ce-2ff5f54585da.png)

**Comment by kwallis** [comment]
What is the actual user impact?

**Comment by jengee** [comment]
Since the UI still displays that the project still exists, it's most likely that the user will also try to click on it. Everytime the user clicks on that project, It will throw the same error over again.

**Comment by jengee** [comment]
There isn't any dialog to tell the user that the project path has been removed or anything. So that user would not know to "trash" the project from the UI.

**Comment by rcruz** [comment]
GUI will detect missing config.xml files and remove projects from the list when appropriate
