### ISSUE TITLE
GUI complains that branding.png is not found

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#48]
1. Start up the UI

On the web inspector console you will see that the it error on the fact that branding.png does not exist

![screen shot 2014-02-04 at 2 08 34 pm](https://f.cloud.github.com/assets/549345/2079883/f53c7110-8dcf-11e3-9fa9-10589fca8ec1.png)

**Comment by kwallis** [comment]
Do we know what this image is supposed to do? Where is it used, and what is the behavoiur when it can't be found?

**Comment by rcruz** [comment]
This image is the WebWorks hippo, which should have been included when creating the installer. With the new UI changes, I believe this hippo image is no longer used.
