### ISSUE TITLE
As a WebWorks developer, I can specify params.json information in the GUI tool on a per project basis

### ISSUE THREAD

**Issue by kwallis** [blackberry/webworks-gui#6]
## Description

Developers can specify information to be passed to the native BlackBerry command line tools by putting items into blackberry10.json. These elements should be exposed in the GUI tool to be edited.

References:
- https://jira.bbqnx.net/browse/BRWSR-14038
- https://issues.apache.org/jira/browse/CB-4931
## Acceptance Criteria
- The developer should be able to specify these items on a per-project basis.
  - common values should have dedicated UI elements to configure
  - There should be a free-form text field that allows arbitrary JSON to be provided by the developer to cover non-common values that could be specified.
  - there may need to be a merge step of the dedicated UI and the free-form text, with dedicated UI taking precedence in case of conflict.
- There will need to be a UX review to determine the best place to put this information and how to structure it. First thoughts is that it would be a section on the existing Build sub-page of the project.
- [TODO] Need to itemize the values that we want to explicitly support in UI elements. First take at the list:
  - "blackberry-signer" options:
    - "-proxyhost": "host"
    - "-proxyport": "port"
    - "-proxyusername": "user name"
    - "-cskpassword": "password"
    - "-keystore": "file"

**Comment by bryanhiggins** [comment]
We also need a way to pass this info through to the certificates page.

**Comment by bryanhiggins** [comment]
Everything has been implemented except "keystore"

**Comment by rcruz** [comment]
To clarify, the "keystore" option is for specifying a .p12 file, not a .csk file.

**Comment by bryanhiggins** [comment]
@rcruz the pull request was closed/merged before addressing my comments

**Comment by rcruz** [comment]
@bryanhiggins Your comments concerning naming, bbidtoken, and full path help text have been included. Is there something else missing?

**Comment by bryanhiggins** [comment]
Missed it since it went straight into master :)
