### ISSUE TITLE
GUI does not work on IE 9 and Safari

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#60]
Found on Win7-64b IE9. None of the buttons, work in IE 9. Can't create a project. Can't import anything. Clicking on the certificates path does nothing either. Noticed a compatibility message on IE9.

Links to the documentation and API reference works.

Safari and Chrome works great too.

![compatibility](https://f.cloud.github.com/assets/549345/2144734/fba0c4c4-938e-11e3-8993-2ffd16345fd4.png)

**Comment by jengee** [comment]
On IE 11, buttons work. I can create multiple projects. I can delete them. I can even build. But I can't seem to add a plugin. Might be a separate error. Will have to check the output log from node.

**Comment by rcruz** [comment]
@themainguru Is that compatibility dark blue (turned on) by default, or was it some setting?

**Comment by jengee** [comment]
For the above image, I just had the cursor hovering over it so that the message would show up. Normally you would only see this:
![normalview](https://f.cloud.github.com/assets/549345/2149815/ccebaa34-93f9-11e3-983c-9abf655f5084.PNG)

**Comment by jengee** [comment]
And if I had it in compatibility mode, I would see a gross looking page:
![compatabilitymode](https://f.cloud.github.com/assets/549345/2149867/5f234646-93fa-11e3-85d8-b5b3f25b9c4b.PNG)

**Comment by jengee** [comment]
Just double checked on Safari (Mac version 6.1.1) and it is unable to display the tool as well.

![screen shot 2014-02-12 at 4 20 31 pm](https://f.cloud.github.com/assets/549345/2153791/2c07379a-942c-11e3-9c04-3f9ee06e028c.png)

**Comment by jengee** [comment]
Safari Windows version (5.1.7) running on win7-64 displays quite nicely.
![wwonsafari5 1 7-win7](https://f.cloud.github.com/assets/549345/2160679/d45479be-94bb-11e3-924c-3f9c993efcce.PNG)

**Comment by kwallis** [comment]
Wondering why this one is targeted at 2.1? Should this not be for the Gold release?

**Comment by kflores772** [comment]
Looks good on IE8 with @rcruz's pull
