### ISSUE TITLE
Missing an image on the Build Tab

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#62]
Found on Win8, IE10 (VM and physical machine) SCM WW SDK 2.0.0.61-Gold

Create a project in the UI
Then click on the Build tab.

On the page there is two spots that show possible images. This does not show up on Chrome. Unable to check on Safari as it cannot even display the UI properly
![possiblemissingpicture](https://f.cloud.github.com/assets/549345/2153777/f94f9388-942b-11e3-9428-5c2304619380.PNG)

**Comment by kflores772** [comment]
Fixed on IE8, IE10, Firefox 27.0.1
