### ISSUE TITLE
Display and formatting issues in UI

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#63]
This is just the general bug to log low priority general display and formatting issues

**Comment by jengee** [comment]
![screen shot 2014-02-13 at 9 22 45 am](https://f.cloud.github.com/assets/549345/2160744/08e9ff86-94bd-11e3-8b05-a5a084d5e789.png)

garbage icon is bleeding over it's box.

Exists on Chrome (v32 on Mac, Safari (v5.1.7 on windows7), and IE (v10 on Windows 8)

**Comment by jengee** [comment]
Formatting on the config page is not pretty either on IE 10 windows 8

![fomatting](https://f.cloud.github.com/assets/549345/2160842/750bfb82-94be-11e3-9bc8-0bdd9099139d.PNG)

**Comment by kwallis** [comment]
We should try to address this for Gold

**Comment by kflores772** [comment]
Issue fixed on Win8 IE10, IE8, Firefox 27.0.1
