### ISSUE TITLE
WebInspector displays your keystore and device password when building

### ISSUE THREAD

**Issue by jengee** [blackberry/webworks-gui#80]
On the build and run, password are purposely hidden so it does not display the device or keystore password. But when you web inspect that page, both passwords are displayed in the console.

![screen shot 2014-02-24 at 1 40 43 pm](https://f.cloud.github.com/assets/549345/2249298/7d794c8e-9d83-11e3-9871-32dff387e7dc.png)

**Comment by rcruz** [comment]
The logging is probably reintroduced by rebasing an old branch.
