### ISSUE TITLE
Odd selection behavior when clicking on puzzle piece or hammer

### ISSUE THREAD

**Issue by jsoref** [blackberry/webworks-gui#85]
IE11

Steps:
1. Open GUI
2. Click on the cog -- note that nothing happens
3. Click Configuration
4. Click on the puzzle piece -- note that it gets some selection
5. Click Plugins
6. Click on the hammer -- note that it gets some selection
7. Click Build

Expected results:
Clicking the cog/puzzle piece/hammer should all behave the same and just like clicking on Configuration, Plugins, or Build

**Comment by jsoref** [comment]
![multiple colored](https://f.cloud.github.com/assets/2119212/2251121/d4a7f2ac-9d98-11e3-86a3-1f34ce62e59a.png)

**Comment by kflores772** [comment]
@rcruz this issue can now be closed
