### ISSUE TITLE
Creating a project with the same path as another project causes issues

### ISSUE THREAD

**Issue by kflores772** [blackberry/webworks-gui#92]
1. Create a project using the gui
2. Create another project with the same path as the first.

Actual outcome:
Two project tabs on the left exist. Only the first created project exists, both tabs point to the same initial created project

Expected outcome:
Error

Using win xp, latest chrome

**Comment by rcruz** [comment]
On windows, the error message output by "webworks create" is not captured on stdout/stderr by node. On OSX, this message is captured correctly and sent back to the GUI for display.

**Comment by kflores772** [comment]
This is a problem in webworks-cli. Closing.
