### ISSUE TITLE
undefined cannot be found

### ISSUE THREAD

**Issue by jsoref** [blackberry/webworks-gui#95]
**Steps**
1. I clicked on io.cordova.hellocordova

**Actual results**
![image](https://f.cloud.github.com/assets/2119212/2297202/8769c286-a0a9-11e3-9492-9a9e6d3febf4.png)

"undefined" (expected as a path?) "can't be found" -- while it's reasonable to try to tell me that a path can't be found...

**Expected results**
if you forgot the path, you should tell me the name of the project as shown in the GUI instead of "undefined"

**Comment by bryanhiggins** [comment]
Duplicate of #90
