### ISSUE TITLE
Dark gray on Blue is hard to read

### ISSUE THREAD

**Issue by jsoref** [blackberry/webworks-gui#96]
Steps:
1. Tap on Configuration
2. Compare the Configuration label (Dark gray on Blue) with the Create button (White on Blue)

**Actual results**
![image](https://f.cloud.github.com/assets/2119212/2297232/09a4e50a-a0aa-11e3-96af-95c4caa04e56.png)

**Expected results**
If white looks good on a color (here it more or less does), then don't use dark gray on that same color (as it looks here, it's bad/hard to read)

**Comment by kflores772** [comment]
1. ![screen shot 2014-03-10 at 11 08 18 am](https://f.cloud.github.com/assets/4356727/2374911/ee4db868-a865-11e3-9cd8-b75cb683be92.png)
2. ![screen shot 2014-03-10 at 11 08 06 am](https://f.cloud.github.com/assets/4356727/2374912/f1697316-a865-11e3-911f-3b9d1bb92b1d.png)

Any preferences for the look?

**Comment by rcruz** [comment]
I prefer option 2

**Comment by jsoref** [comment]
@rcruz : the problem is that those colors look like the buttons which are clickable, this isn't a clickable thing, it's an already clicked thing -- in the top screen, only Configuration/Build can be clicked, in the bottom, only Configuration and Plugins can be clicked.

I prefer option 1

**Comment by rcruz** [comment]
Option 1 works as it appears clearly highlighted
